apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collection-api
  labels:
    app: data-collection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collection-api
  template:
    metadata:
      labels:
        app: data-collection-api
    spec:
      containers:
      - name: data-collection-api-container
        image: awesomecosmonaut/data-collection-api-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "250m"